export const products = [
    {
        id: 1,
        tittle: "Nike Zoom Mercurial",
        price: "140000",
        stock: 4,
        color: "White-Baltic Blue-Pink Blast",
        description:
            "Botines de pasto, impulsa tu velocidad y profundidad para el despegue.",
        category: "nike",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687983307/bota-nike-air-zoom-mercurial-superfly-9-elite-fg-white-baltic-blue-pink-blast-0_itrchm.webp",
    },
    {
        id: 2,
        tittle: "Nike Mercurial",
        price: "139999",
        stock: 2,
        color: " Pink Spell-Volt-Gridiron",
        description:
            "Botines de pasto, impulsa tu velocidad y profundidad para el despegue.",
        category: "nike",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687983088/bota-nike-air-zoom-mercurial-superfly-9-pro-fg-rosa-0_zpbdjk.webp",
    },
    {
        id: 3,
        tittle: "Nike Gripknit Phantom",
        price: "152000",
        stock: 5,
        color: "Blanco y azul celeste",
        description:
            "Ajustado para el toque. A partir de las características del Phantom GT, el Nike Phantom GT2 Elite FG presenta un diseño actualizado y unos patrones gráficos en relieve para optimizar el giro y controlar la trayectoria de la pelota.",
        category: "nike",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687983436/bota-nike-phantom-gx-elite-df-sg-pro-p-baltic-bluepink-blast-white-laser-blue-black-0_f7e08p.webp",
    },
    {
        id: 4,
        tittle: "Nike Phantom GT2 Elite",
        price: "135000",
        stock: 6,
        color: "Barely Volt-Gridiron-Barely Grp",
        description:
            "Ajustado para el toque. A partir de las características del Phantom GT, el Nike Phantom GT2 Elite FG presenta un diseño actualizado y unos patrones gráficos en relieve para optimizar el giro y controlar la trayectoria de la pelota.",
        category: "nike",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687983530/bota-nike-phantom-gx-elite-df-sg-pro-barely-volt-gridiron-barely-grp-0_evuvwp.webp",
    },
    {
        id: 5,
        tittle: "Nike Tiempo Legend 9",
        price: "46000",
        stock: 8,
        color: "White-Black-Baltic Blue",
        description:
            "El Nike Tiempo Legend 9 Academy SG-Pro AC, uno de nuestros Tiempo más ligeros hasta la fecha, te permite ir a la ofensiva con un diseño de perfil bajo que se reinventa para los atacantes.",
        category: "nike",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687982875/bota-nike-tiempo-legend-9-elite-fg-blanco-0_h7yjvc.webp",
    },
    {
        id: 6,
        tittle: "Nike Tiempo Legend 9",
        price: "52000",
        stock: 3,
        color: "Space Purple-White-Off Noir",
        description:
            "El Nike Tiempo Legend 9 Academy SG-Pro AC, uno de nuestros Tiempo más ligeros hasta la fecha, te permite ir a la ofensiva con un diseño de perfil bajo que se reinventa para los atacantes.",
        category: "nike",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687982983/bota-nike-tiempo-legend-9-elite-fg-space-purple-white-off-noir-0_znxh0t.webp",
    },
    {
        id: 7,
        tittle: "Adidas Predator Edge+",
        price: "102300",
        stock: 1,
        color: "Solar Red-Solar Green-Black",
        description:
            "Estas botas de fútbol para jóvenes te ayudan a controlar el balón con una parte superior de Control Zone que contiene áreas estratégicamente ubicadas de impresión que mejoran el agarre.",
        category: "adidas",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687983667/bota-adidas-predator-edge-sg-solar-red-solar-green-black-0_yxx3wi.webp",
    },
    {
        id: 8,
        tittle: "Adidas Predator Edge.1",
        price: "95000",
        stock: 3,
        color: "White-Solar Yellow-Power Blue",
        description:
            "Estas botas de fútbol para jóvenes te ayudan a controlar el balón con una parte superior de Control Zone que contiene áreas estratégicamente ubicadas de impresión que mejoran el agarre.",
        category: "adidas",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687983758/bota-adidas-predator-edge-.1-sg-white-solar-yellow-power-blue-0_jbkb1b.webp",
    },
    {
        id: 9,
        tittle: "Adidas X SpeedPortal",
        price: "67000",
        stock: 5,
        color: "Solar Gold-Core Black-Solar Orange",
        description:
            "Desarrolladas para el jugador que compite al máximo nivel y que busca unas botas de gama alta con las que exprimir al máximo su velocidad sobre campos de fútbol de hierba natural seca o húmeda.",
        category: "adidas",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687983885/bota-adidas-x-speedportal-fg-solar-gold-core-black-solar-orange-0_webavw.webp",
    },
    {
        id: 10,
        tittle: "Adidas X SpeedPortal.1",
        price: "67000",
        stock: 2,
        color: "Dorado",
        description:
            "Desarrolladas para el jugador que compite al máximo nivel y que busca unas botas de gama alta con las que exprimir al máximo su velocidad sobre campos de fútbol de hierba natural seca o húmeda.",
        category: "adidas",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687559792/204740b71-f4e3a04aa88d338ee716717489215459-640-0_gm2tqb.webp",
    },
    {
        id: 11,
        tittle: "Adidas Copa Pure+ FG",
        price: "87000",
        stock: 3,
        color: "White-Solar Orange",
        description:
            "Hechos para jugadores de máximo nivel que busquen una bota de piel natural de rendimiento profesional y quienes pongan la comodidad por encima de cualquier otro punto. Botas para usar en campos de hierba natural.",
        category: "adidas",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687559968/bota-adidas-copa-pure-fg-off-whiteteam-solar-orangeoff-white-0_wykm9u.webp",
    },
    {
        id: 12,
        tittle: "Adidas Copa Sense.1 SG",
        price: "78500",
        stock: 7,
        color: "Yellow-Solar Red-Black",
        description:
            "Hechos para jugadores de máximo nivel que busquen una bota de piel natural de rendimiento profesional y quienes pongan la comodidad por encima de cualquier otro punto. Botas para usar en campos de hierba natural húmeda o mojada.",
        category: "adidas",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687560128/bota-adidas-copa-sense-.1-sg-solar-yellow-solar-red-black-0_gclsjo.webp",
    },
    {
        id: 13,
        tittle: "Puma Future Ultimate",
        price: "144000",
        stock: 5,
        color: "Violet-Black-Yellow Sizzle-Rickie Orange",
        description:
            "Hecha para aquellos jugadores que busquen una bota de gama alta para competir a nivel profesional o semiprofesional, que ofrezca ajuste y comodidad a partes iguales. Para usar en campos de hierba natural y campos de hierba artificial de última generación.",
        category: "puma",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687560432/bota-puma-future-ultimate-fgag-violet-black-yellow-sizzle-rickie-orang-0_dpd5bd.webp",
    },
    {
        id: 14,
        tittle: "Puma Future Ultimate",
        price: "135799",
        stock: 8,
        color: "Yellow- Black-Electric Peppermint",
        description:
            "Hecha para aquellos jugadores que busquen una bota de gama alta para competir a nivel profesional o semiprofesional, que ofrezca ajuste y comodidad a partes iguales. Para usar en campos de hierba natural y campos de hierba artificial de última generación.",
        category: "puma",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687560566/bota-puma-future-ultimate-fgag-amarillo-0_jnaxnw.webp",
    },
    {
        id: 15,
        tittle: "Puma Ultra Ultimate CP",
        price: "97000",
        stock: 2,
        color: "Navy- White-Bright Aqua",
        description:
            "Botines de rendimiento profesional desarrollada para usarlos en campos de césped natural y césped artificial. Orientada a jugadores que busquen botines ligeros y con un ajuste personalizado",
        category: "puma",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687561014/bota-puma-ultra-ultimate-fgag-navy-white-bright-aqua-0_bc5fdm.webp",
    },
    {
        id: 16,
        tittle: "Puma Ultra Ultimate CP",
        price: "97000",
        stock: 3,
        color: "White-Lime Smash-Clyde Royal",
        description:
            "Botines de rendimiento profesional desarrollada para usarlos en campos de césped natural y césped artificial. Orientada a jugadores que busquen botines ligeros y con un ajuste personalizado.",
        category: "puma",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687560831/bota-puma-ultra-ultimate-cp-fgag-white-lime-smash-clyde-royal-0_hi9xa0.webp",
    },
    {
        id: 17,
        tittle: "Puma King Ultimate",
        price: "74000",
        stock: 6,
        color: "White-Black-Fast Yellow",
        description:
            "Botines de rendimiento profesional desarrollada para ser usada en campos de césped natural húmeda. Orientada a jugadores que busquen botines para competir priorizando la comodidad y las sensaciones con el balón.",
        category: "puma",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687561218/bota-puma-king-ultimate-fgag-blanco-0_wtu9ev.webp",
    },
    {
        id: 18,
        tittle: "Puma King Ultimate",
        price: "73000",
        stock: 5,
        color: "Black-White-Fire Orchid",
        description:
            "Botines de rendimiento profesional desarrollada para ser usada en campos de césped natural húmeda. Orientada a jugadores que busquen botines para competir priorizando la comodidad y las sensaciones con el balón.",
        category: "puma",
        img: "https://res.cloudinary.com/dqonbozpq/image/upload/v1687561141/bota-puma-king-ultimate-sg-black-white-fire-orchid-0_awqdqz.webp",
    },
];
